name: BetterMobsEnd
version: 1.0.0
main: MadoxMc\EndMobs\Main
api: 5.0.0
author: MadoxMc
editor: MadoxMC
commands:
  killendmobs:
    usage: "/killendmobs"
    description: "Kill all End Mobs"
    permission: mobsend.operator
  listendmobs:
    usage: "/listendmobs"
    description: "List all End Mobs"
    permission: mobsend.operator
  summonend:
    usage: "/summonend <type> [quantity]"
    description: "Summon a End Mob"
    permission: mobsend.operator
permissions:
  mobsend.operator:
    description: allow using end mob commands
    default: op
